### ISSUE TITLE
Running `tsc` failed

### ISSUE THREAD

**Issue by blai** [pleerock/routing-controllers-koa-demo#1]
Following readme, and failed at step 2 `tsc`, it has the following error

`node_modules/routing-controllers/middleware/ErrorMiddlewareInterface.d.ts(1,49): error TS2307: Cannot find module 'http'.`

**Comment by blai** [comment]
BTW,

```
❯ tsc -v
Version 1.8.10
```

**Comment by pleerock** [comment]
is it the only error you have? try to install latest version, I have updated routing-controllers version

**Comment by blai** [comment]
Perfect, works now. Thanks.
